In [1]:
import numpy as np
a= np.array([5,5,5,2])
a

array([5, 5, 5, 2])

In [2]:
type(a)

numpy.ndarray

In [3]:
len(a)

4

In [4]:
b=np.array([[5,5,1,5],[2,3,5,4],[5,5,5,8],[5,7,2,1]])
b

array([[5, 5, 1, 5],
       [2, 3, 5, 4],
       [5, 5, 5, 8],
       [5, 7, 2, 1]])

In [5]:
len(b)

4

In [6]:
type(b)

numpy.ndarray

In [7]:
import numpy as np
a= np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [8]:
b=np.zeros(2)
b

array([0., 0.])

In [9]:
c=np.ones(3)
c

array([1., 1., 1.])

In [10]:
#create an empty arrey with 2 elemnts
d=np.empty(3)
d

array([1., 1., 1.])

In [12]:
#write arange of elemrnt
e=np.arange(6)
e

array([0, 1, 2, 3, 4, 5])

In [14]:
#with spaces of arange of elemnts
f=np.arange(2,20)
f


array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [16]:
#continue
g=np.arange(2,20,2)
g

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
#linerly space arrays
h=np.linspace(0,10,num=5)  #give use 5 number
h

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [18]:
#specific data type in array
i=np.ones(5,dtype=np.int8)
i

array([1, 1, 1, 1, 1], dtype=int8)

In [20]:
j=np.ones(3,dtype=np.float64)
j

array([1., 1., 1.])

### 

## 2-D Arrays

In [32]:
# import numpy as np
np.zeros((3,4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [33]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [34]:
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## 3-D Array

In [38]:
#making and reshaping a 3D Array
c=np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])