# Numpy Paractice 

In [1]:
#import library
import numpy as np

# Create an array using by numpy 

In [2]:
# 1 D array
food=np.array(["smaosa","pakora","raita"])
food

array(['smaosa', 'pakora', 'raita'], dtype='<U6')

In [3]:
price=np.array([5,5,5])
price

array([5, 5, 5])

In [4]:
type(food)

numpy.ndarray

In [5]:
type(price)

numpy.ndarray

In [6]:
len(food)

3

In [7]:
price[2]

5

In [8]:
price[0:]

array([5, 5, 5])

In [9]:
food[0]

'smaosa'

In [10]:
#zeros
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [11]:
#ones
np.ones(4)

array([1., 1., 1., 1.])

In [12]:
#empity
np.empty(4)

array([1., 1., 1., 1.])

In [13]:
# range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
#specify
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [15]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
# Table of 5
np.arange(5,55,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [17]:
#line space
np.linspace(1,10, num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [18]:
#spacify you data type
np.ones(50, dtype=np.int64)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1], dtype=int64)

In [19]:
np.ones(50, dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# Array Function

In [20]:
a=np.array([10,12,15,2,4,6,500,320,0.5,10.3])
a

array([ 10. ,  12. ,  15. ,   2. ,   4. ,   6. , 500. , 320. ,   0.5,
        10.3])

In [21]:
a.sort()
a

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 320. ,
       500. ])

In [22]:
b=np.array([5,1,55,40,52.3,25.0,2])
b

array([ 5. ,  1. , 55. , 40. , 52.3, 25. ,  2. ])

In [23]:
c=np.concatenate((a,b))
c

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 320. ,
       500. ,   5. ,   1. ,  55. ,  40. ,  52.3,  25. ,   2. ])

In [24]:
c.sort()
c

array([  0.5,   1. ,   2. ,   2. ,   4. ,   5. ,   6. ,  10. ,  10.3,
        12. ,  15. ,  25. ,  40. ,  52.3,  55. , 320. , 500. ])

In [25]:
x= np.array([[1,2],[5,4]])
x

array([[1, 2],
       [5, 4]])

In [26]:
y=np.array([[6,7], [7,8]])
y

array([[6, 7],
       [7, 8]])

In [27]:
np.concatenate((x,y))

array([[1, 2],
       [5, 4],
       [6, 7],
       [7, 8]])

In [28]:
np.concatenate((x,y),axis=0)

array([[1, 2],
       [5, 4],
       [6, 7],
       [7, 8]])

In [29]:
np.concatenate((x,y),axis=1)

array([[1, 2, 6, 7],
       [5, 4, 7, 8]])

In [31]:
a = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [32]:
a.ndim

3

In [33]:
# 2-D array
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
b.ndim

2

In [35]:
a.size

24

In [36]:
b.size

9

In [38]:
a

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [37]:
a.shape

(3, 2, 4)

In [40]:
b.shape

(3, 3)

In [41]:
a=np.arange(9) #3*3=9
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [43]:
#reshape
b=a.reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [50]:
#reshape
np.reshape(a,newshape=(1,9), order="c")

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [51]:
# conver 1-D to 2D
a=np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
a.shape

(9,)

In [55]:
#rowwase 2-D
b = a[np.newaxis, :]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [56]:
b.shape

(1, 9)

In [57]:
#colume wize
c = a[:,np.newaxis]
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [58]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
# indexing
a[2:9]

array([3, 4, 5, 6, 7, 8, 9])

In [60]:
a*6

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54])

In [61]:
a+6

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15])

In [65]:
a.sum()

45

In [67]:
a.mean()

5.0

In [68]:
a.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'